import React from 'react'
import Layout from '/common/Layout/lay-out'

const PrivacyPolicy = () => {
    return (
        <>
            <div className='w-full h-full flex flex-col md:py-6 md:px-[4rem]'>

                <div className='flex justify-center px-2  md:pt-[4rem] futuraMedium font-semibold text-4xl'>Privacy Policy</div>
                {data.map((item, index) => {
                    return (
                        <div key={item.id} className='flex flex-col py-6 md:py-[1rem] justify-center px-[1.5rem] overflow-x-clip md:px-[10rem]'>
                            <h1 className='futuraMedium text-lg py-[1rem] md:py-[1rem]'>{item.id}</h1>
                            <p className='futura'>{item.desc}</p>
                        </div>
                    )
                }

                )}


            </div>
        </>
    )
}

PrivacyPolicy.getLayout = (page) => {
    return <Layout>{page}</Layout>
}

const data = [{ "id": "Data protection", "desc": "This data protection declaration clarifies the type, scope and purpose of the processing of personal data (hereinafter referred to as data) within our online offer and the websites, functions and content associated with it, as well as external online presences, such as our social media profile (hereinafter referred to as collectively referred to as Online Offering). With regard to the terms used, such as processing or person responsible, we refer to the definitions in Article 4 of the General Data Protection Regulation (GDPR)" },
{ "id": "Categories of data subjects", "desc": "Visitors and users of the online offer (in the following we refer to the persons concerned collectively as users)" }, { "id": "Terms used", "desc": "ersonal data means any information relating to an identified or identifiable natural person (hereinafter data subject); an identifiable natural person is one who can be identified directly or indirectly, in particular by means of assignment to an identifier such as a name, an identification number, location data, an online identifier (e.g. cookie) or one or more special features, are an expression of the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person.Processing is any process or series of processes carried out with or without the aid of automated processes in connection with personal data. The term is broad and encompasses practically every handling of data. Pseudonymizatio means the processing of personal data in such a way that the personal data can no longer be assigned to a specific data subject without the use of additional information, provided that this additional information is stored separately and is subject to technical and organizational measures that ensure that the personal data not assigned to an identified or identifiable natural person. Profiling any type of automated processing of personal data, which consists in using this personal data to evaluate certain personal aspects relating to a natural person, in particular aspects related to work performance, economic situation, health, personal Analyze or predict that natural person's preferences, interests, reliability, behavior, whereabouts or relocation. The responsible person is the natural or legal person, authority, institution or other body that alone or jointly with others decides on the purposes and means of processing personal data. Processor means a natural or legal person, public authority, agency or other body that processes personal data on behalf of the person responsible." }
    , { "id": "Relevant legal bases", "desc": "In accordance with Art. 13 GDPR, we will inform you of the legal basis for our data processing. If the legal basis is not mentioned in the data protection declaration, the following applies: The legal basis for obtaining consent is Art. 6 (1) lit. a and Art Answering inquiries is Article 6(1)(b) GDPR, the legal basis for processing to fulfill our legal obligations is Article 6(1)(c) GDPR, and the legal basis for processing to safeguard our legitimate interests is Article 6(1)(c) GDPR 6 Paragraph 1 lit. f GDPR. In the case," }
    , { "id": "Safety measures", "desc": "In accordance with Art. 32 GDPR, we take appropriate technical measures, taking into account the state of the art, the implementation costs and the type, scope, circumstances and purposes of the processing as well as the different probability of occurrence and severity of the risk for the rights and freedoms of natural persons and organizational measures to ensure a level of protection appropriate to the risk.The measures include, in particular, securing the confidentiality, integrity and availability of data by controlling physical access to the data, as well as access, input, transfer, securing availability and their separation. Furthermore, we have set up procedures that ensure the exercise of data subject rights, deletion of data and reaction to data threats. Furthermore, we already take the protection of personal data into account during the development or selection of hardware, software and processes, in accordance with the principle of data protection through technology design and through data protection-friendly default settings (Article 25 GDPR)." }
    , { "id": "Cooperation with processors and third parties", "desc": "If, as part of our processing, we disclose data to other people and companies (contract processors or third parties), transmit it to them or otherwise grant them access to the data, this is only done on the basis of legal permission (e.g. if the data is transmitted to third parties, as to payment service providers, pursuant to Art. 6 Para. 1 lit. b GDPR is required for the fulfillment of the contract), you have consented, a legal obligation provides for this or on the basis of our legitimate interests (e.g. when using agents, web hosts, etc.).If we commission third parties to process data on the basis of a so-called order processing contract, this is done on the basis of Art. 28 DSGVO." }
    , { "id": "Rights of data subjects", "desc": "You have the right to request confirmation as to whether the data in question is being processed and to request information about this data as well as further information and a copy of the data in accordance with Art. 15 GDPR.You have accordingly. Art. 16 DSGVO the right to request the completion of the data concerning you or the correction of incorrect data concerning you.In accordance with Art. 17 GDPR, you have the right to demand that the data in question be deleted immediately, or alternatively, in accordance with Art. 18 GDPR, to demand a restriction of the processing of the data.You have the right to request that you receive the data that you have provided to us in accordance with Art. 20 GDPR and to request that it be transmitted to other responsible parties.You also have the right, in accordance with Article 77 GDPR, to lodge a complaint with the competent supervisory authority." }
    , { "id": "Cookies and the right to object to direct advertising", "desc": "Cookies are small files that are stored on users' computers. Different information can be stored within the cookies. A cookie is primarily used to store information about a user (or the device on which the cookie is stored) during or after their visit to an online offer. Temporary cookies, or session cookies or transient cookies, are cookies that are deleted after a user leaves an online offer and closes his browser. In such a cookie, for example, the content of a shopping cart in an online shop or a login status can be saved. Permanent or persistent refers to cookies that remain stored even after the browser is closed. For example, the login status can be saved, if the users visit them after several days. The interests of the users can also be stored in such a cookie, which are used for range measurement or marketing purposes. Third-party cookies are cookies that are offered by providers other than the person responsible for operating the online offer (otherwise, if they are only their cookies, we speak of first-party cookies). We can use temporary and permanent cookies and explain this in our data protection declaration. If users do not want cookies to be stored on their computer, they are asked to deactivate the corresponding option in their browser's system settings. Saved cookies can be deleted in the system settings of the browser. The exclusion of cookies can lead to functional restrictions of this online offer. A general objection to the use of cookies for online marketing purposes can be raised for a large number of services, especially in the case of tracking, via the US website http://www.aboutads.info/choices/ or the EU website http://www.youronlinechoices.com/. Furthermore, the storage of cookies can be achieved by switching them off in the browser settings. Please note that in this case not all functions of this online offer can be used." }
    , { "id": "Google Analytics", "desc": "On the basis of our legitimate interests (ie interest in the analysis, optimization and economic operation of our online offer within the meaning of Art. 6 Para. 1 lit. f. DSGVO) we use Google Analytics, a web analysis service provided by Google LLC (Google). Google uses cookies. The information generated by the cookie about the use of the online offer by the user is usually transmitted to a Google server in the USA and stored there. Google is certified under the Privacy Shield Agreement and thus offers a guarantee to comply with European data protection law (https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&status=Active). Google will use this information on our behalf to evaluate the use of our online offer by users, to compile reports on the activities within this online offer and to provide us with other services related to the use of this online offer and internet usage. Pseudonymous user profiles can be created from the processed data. We only use Google Analytics with activated IP anonymization. This means that the IP address of the user is shortened by Google within member states of the European Union or in other contracting states of the Agreement on the European Economic Area. Only in exceptional cases will the full IP address be sent to a Google server in the USA and shortened there. The IP address transmitted by the user's browser is not merged with other Google data. Users can prevent the storage of cookies by setting their browser software accordingly; In addition, users can prevent the data generated by the cookie and related to their use of the online offer from being collected and processed by Google by downloading and installing the browser plug-in available under the following link: http://tools .google.com/dlpage/gaoptout?hl=en. You can find more information on data use by Google, setting and objection options in Google's data protection declaration (https://policies.google.com/technologies/ads) and in the settings for the display of advertisements by Google (https:// adssettings.google.com/authenticated).The personal data of the users will be deleted or made anonymous after 14 months.You can object to the collection by the Facebook pixel and the use of your data to display Facebook ads. In order to set which types of advertisements are displayed to you within Facebook, you can visit the page set up by Facebook and follow the instructions for setting usage-based adverting." }
    , { "id": "Facebook-Pixel, Custom Audiences und Facebook-Conversion", "desc": "Due to our legitimate interests in the analysis, optimization and economic operation of our online offer and for these purposes, the so-called Facebook pixel of the social network Facebook, which is operated by Facebook Inc., 1 Hacker Way, Menlo Park, CA 94025 , USA, or if you are based in the EU, Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland (Facebook).Facebook is certified under the Privacy Shield Agreement and thus offers a guarantee to comply with European data protection law (https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&status=Active).With the help of the Facebook pixel, Facebook is able to determine the visitors of our online offer as a target group for the display of advertisements (so-called Facebook Ads). Accordingly, we use the Facebook pixel to only display the Facebook ads we have placed to those Facebook users who have also shown an interest in our online offering or who have certain characteristics (e.g. interests in certain topics or products, which are based on the visited website). websites are determined), which we transmit to Facebook (so-called Custom Audiences). With the help of the Facebook pixel, we also want to ensure that our Facebook ads correspond to the potential interests of users and are not annoying.he processing of the data by Facebook takes place within the framework of Facebook's data usage guidelines. Accordingly, general information on the display of Facebook ads in Facebook's data usage guidelines: https://www.facebook.com/policy.php. You can find specific information and details about the Facebook pixel and how it works in the Facebook help area: https://www.facebook.com/business/help/651294705016616." }
    , { "id": "Instagram", "desc": "Functions and content of the Instagram service offered by Instagram Inc., 1601 Willow Road, Menlo Park, CA, 94025, USA, can be integrated within our online offer. This can include, for example, content such as images, videos or text and buttons with which users can express their liking for the content, the authors of the content or subscribe to our posts. If the users are members of the Instagram platform, Instagram can assign the above-mentioned content and functions to the user profiles there. Instagram privacy policy: http://instagram.com/about/legal/privacy/.Created with Datenschutz-Generator.de by RA Dr. Thomas Schwenke" }
]



export default PrivacyPolicy